-- ================================================
-- 反向還原小鶴雙拼 → 拼音 → 注音
-- ================================================

local bopomofo = {}

-- Xiaohe Shuangpin (inverse mapping)
local SHUANGPIN_TO_PINYIN = {
["aa"]="a",
["ai"]="ai",
["an"]="an",
["ah"]="ang",
["ao"]="ao",
["ba"]="ba",
["bd"]="bai",
["bj"]="ban",
["bh"]="bang",
["bc"]="bao",
["bw"]="bei",
["bf"]="ben",
["bg"]="beng",
["bi"]="bi",
["bm"]="bian",
["bn"]="biao",
["bp"]="bie",
["bb"]="bin",
["bk"]="bing",
["bo"]="bo",
["bu"]="bu",
["ca"]="ca",
["cd"]="cai",
["cj"]="can",
["ch"]="cang",
["cc"]="cao",
["ce"]="ce",
["cf"]="cen",
["cg"]="ceng",
["ia"]="cha",
["id"]="chai",
["ij"]="chan",
["ih"]="chang",
["ic"]="chao",
["ie"]="che",
["if"]="chen",
["ig"]="cheng",
["ii"]="chi",
["is"]="chong",
["iz"]="chou",
["iu"]="chu",
["ix"]="chua",
["ik"]="chuai",
["ir"]="chuan",
["il"]="chuang",
["iv"]="chui",
["iy"]="chun",
["io"]="chuo",
["ci"]="ci",
["cs"]="cong",
["cz"]="cou",
["cu"]="cu",
["cr"]="cuan",
["cv"]="cui",
["cy"]="cun",
["co"]="cuo",
["da"]="da",
["dd"]="dai",
["dj"]="dan",
["dh"]="dang",
["dc"]="dao",
["de"]="de",
["dw"]="dei",
["df"]="den",
["dg"]="deng",
["di"]="di",
["dm"]="dian",
["dl"]="diang",
["dn"]="diao",
["dp"]="die",
["dk"]="ding",
["dq"]="diu",
["ds"]="dong",
["dz"]="dou",
["du"]="du",
["dr"]="duan",
["dv"]="dui",
["dy"]="dun",
["do"]="duo",
["ee"]="e",
["ei"]="ei",
["en"]="en",
["er"]="er",
["fa"]="fa",
["fj"]="fan",
["fh"]="fang",
["fw"]="fei",
["ff"]="fen",
["fg"]="feng",
["fo"]="fo",
["fz"]="fou",
["fu"]="fu",
["ga"]="ga",
["gd"]="gai",
["gj"]="gan",
["gh"]="gang",
["gc"]="gao",
["ge"]="ge",
["gw"]="gei",
["gf"]="gen",
["gg"]="geng",
["gs"]="gong",
["gz"]="gou",
["gu"]="gu",
["gx"]="gua",
["gk"]="guai",
["gr"]="guan",
["gl"]="guang",
["gv"]="gui",
["gy"]="gun",
["go"]="guo",
["ha"]="ha",
["hd"]="hai",
["hj"]="han",
["hh"]="hang",
["hc"]="hao",
["he"]="he",
["hw"]="hei",
["hf"]="hen",
["hg"]="heng",
["hs"]="hong",
["hz"]="hou",
["hu"]="hu",
["hx"]="hua",
["hk"]="huai",
["hr"]="huan",
["hl"]="huang",
["hv"]="hui",
["hy"]="hun",
["ho"]="huo",
["ji"]="ji",
["jx"]="jia",
["jm"]="jian",
["jl"]="jiang",
["jn"]="jiao",
["jp"]="jie",
["jb"]="jin",
["jk"]="jing",
["js"]="jiong",
["jq"]="jiu",
["ju"]="ju",
["jr"]="juan",
["jt"]="jue",
["jy"]="jun",
["ka"]="ka",
["kd"]="kai",
["kj"]="kan",
["kh"]="kang",
["kc"]="kao",
["ke"]="ke",
["kw"]="kei",
["kf"]="ken",
["kg"]="keng",
["ks"]="kong",
["kz"]="kou",
["ku"]="ku",
["kx"]="kua",
["kk"]="kuai",
["kr"]="kuan",
["kl"]="kuang",
["kv"]="kui",
["ky"]="kun",
["ko"]="kuo",
["la"]="la",
["ld"]="lai",
["lj"]="lan",
["lh"]="lang",
["lc"]="lao",
["le"]="le",
["lw"]="lei",
["lg"]="leng",
["li"]="li",
["lx"]="lia",
["lm"]="lian",
["ll"]="liang",
["ln"]="liao",
["lp"]="lie",
["lb"]="lin",
["lk"]="ling",
["lq"]="liu",
["lo"]="lo",
["ls"]="long",
["lz"]="lou",
["lu"]="lu",
["lr"]="luan",
["ly"]="lun",
["lo"]="luo",
["lv"]="lü",
["lt"]="lüe",
["ma"]="ma",
["md"]="mai",
["mj"]="man",
["mh"]="mang",
["mc"]="mao",
["me"]="me",
["mw"]="mei",
["mf"]="men",
["mg"]="meng",
["mi"]="mi",
["mm"]="mian",
["mn"]="miao",
["mp"]="mie",
["mb"]="min",
["mk"]="ming",
["mq"]="miu",
["mo"]="mo",
["mz"]="mou",
["mu"]="mu",
["na"]="na",
["nd"]="nai",
["nj"]="nan",
["nh"]="nang",
["nc"]="nao",
["ne"]="ne",
["nw"]="nei",
["nf"]="nen",
["ng"]="neng",
["ni"]="ni",
["nx"]="nia",
["nm"]="nian",
["nl"]="niang",
["nn"]="niao",
["np"]="nie",
["nb"]="nin",
["nk"]="ning",
["nq"]="niu",
["ns"]="nong",
["nz"]="nou",
["nu"]="nu",
["nr"]="nuan",
["ny"]="nun",
["no"]="nuo",
["nv"]="nü",
["nt"]="nüe",
["oo"]="o",
["ou"]="ou",
["pa"]="pa",
["pd"]="pai",
["pj"]="pan",
["ph"]="pang",
["pc"]="pao",
["pw"]="pei",
["pf"]="pen",
["pg"]="peng",
["pi"]="pi",
["pm"]="pian",
["pn"]="piao",
["pp"]="pie",
["pb"]="pin",
["pk"]="ping",
["po"]="po",
["pz"]="pou",
["pu"]="pu",
["qi"]="qi",
["qx"]="qia",
["qm"]="qian",
["ql"]="qiang",
["qn"]="qiao",
["qp"]="qie",
["qb"]="qin",
["qk"]="qing",
["qs"]="qiong",
["qq"]="qiu",
["qu"]="qu",
["qr"]="quan",
["qt"]="que",
["qy"]="qun",
["rj"]="ran",
["rh"]="rang",
["rc"]="rao",
["re"]="re",
["rf"]="ren",
["rg"]="reng",
["ri"]="ri",
["rs"]="rong",
["rz"]="rou",
["ru"]="ru",
["rr"]="ruan",
["rv"]="rui",
["ry"]="run",
["ro"]="ruo",
["sa"]="sa",
["sd"]="sai",
["sj"]="san",
["sh"]="sang",
["sc"]="sao",
["se"]="se",
["sw"]="sei",
["sf"]="sen",
["sg"]="seng",
["ua"]="sha",
["ud"]="shai",
["uj"]="shan",
["uh"]="shang",
["uc"]="shao",
["ue"]="she",
["uw"]="shei",
["uf"]="shen",
["ug"]="sheng",
["ui"]="shi",
["us"]="shong",
["uz"]="shou",
["uu"]="shu",
["ux"]="shua",
["uk"]="shuai",
["ur"]="shuan",
["ul"]="shuang",
["uv"]="shui",
["uy"]="shun",
["uo"]="shuo",
["si"]="si",
["ss"]="song",
["sz"]="sou",
["su"]="su",
["sr"]="suan",
["sv"]="sui",
["sy"]="sun",
["so"]="suo",
["ta"]="ta",
["td"]="tai",
["tj"]="tan",
["th"]="tang",
["tc"]="tao",
["te"]="te",
["tg"]="teng",
["ti"]="ti",
["tm"]="tian",
["tn"]="tiao",
["tp"]="tie",
["tk"]="ting",
["ts"]="tong",
["tz"]="tou",
["tu"]="tu",
["tr"]="tuan",
["tv"]="tui",
["ty"]="tun",
["to"]="tuo",
["wa"]="wa",
["wd"]="wai",
["wj"]="wan",
["wh"]="wang",
["ww"]="wei",
["wf"]="wen",
["wg"]="weng",
["wo"]="wo",
["wu"]="wu",
["xi"]="xi",
["xx"]="xia",
["xm"]="xian",
["xl"]="xiang",
["xn"]="xiao",
["xp"]="xie",
["xb"]="xin",
["xk"]="xing",
["xs"]="xiong",
["xq"]="xiu",
["xu"]="xu",
["xr"]="xuan",
["xt"]="xue",
["xy"]="xun",
["ya"]="ya",
["yj"]="yan",
["yh"]="yang",
["yc"]="yao",
["ye"]="ye",
["yi"]="yi",
["yb"]="yin",
["yk"]="ying",
["ys"]="yong",
["yz"]="you",
["yu"]="yu",
["yr"]="yuan",
["yt"]="yue",
["yy"]="yun",
["za"]="za",
["zd"]="zai",
["zj"]="zan",
["zh"]="zang",
["zc"]="zao",
["ze"]="ze",
["zw"]="zei",
["zf"]="zen",
["zg"]="zeng",
["va"]="zha",
["vd"]="zhai",
["vj"]="zhan",
["vh"]="zhang",
["vc"]="zhao",
["ve"]="zhe",
["vw"]="zhei",
["vf"]="zhen",
["vg"]="zheng",
["vi"]="zhi",
["vs"]="zhong",
["vz"]="zhou",
["vu"]="zhu",
["vx"]="zhua",
["vk"]="zhuai",
["vr"]="zhuan",
["vl"]="zhuang",
["vv"]="zhui",
["vy"]="zhun",
["vo"]="zhuo",
["zi"]="zi",
["zs"]="zong",
["zz"]="zou",
["zu"]="zu",
["zr"]="zuan",
["zv"]="zui",
["zy"]="zun",
["zo"]="zuo",

-- Initial constants
["i"]="ch",
["u"]="sh",
["v"]="zh",
}

-- Mapping: toneless pinyin (string) -> zhuyin (string of bopomofo symbols)
-- Supports both 'ü' and 'v' for the ü vowel (lv/nv or lü/nü)

local PINYIN_TO_ZHUYIN = {
["a"]="ㄚ",
["ai"]="ㄞ",
["an"]="ㄢ",
["ang"]="ㄤ",
["ao"]="ㄠ",
["ba"]="ㄅㄚ",
["bai"]="ㄅㄞ",
["ban"]="ㄅㄢ",
["bang"]="ㄅㄤ",
["bao"]="ㄅㄠ",
["bei"]="ㄅㄟ",
["ben"]="ㄅㄣ",
["beng"]="ㄅㄥ",
["bi"]="ㄅㄧ",
["bian"]="ㄅㄧㄢ",
["biao"]="ㄅㄧㄠ",
["bie"]="ㄅㄧㄝ",
["bin"]="ㄅㄧㄣ",
["bing"]="ㄅㄧㄥ",
["bo"]="ㄅㄛ",
["bu"]="ㄅㄨ",
["ca"]="ㄘㄚ",
["cai"]="ㄘㄞ",
["can"]="ㄘㄢ",
["cang"]="ㄘㄤ",
["cao"]="ㄘㄠ",
["ce"]="ㄘㄜ",
["cen"]="ㄘㄣ",
["ceng"]="ㄘㄥ",
["cha"]="ㄔㄚ",
["chai"]="ㄔㄞ",
["chan"]="ㄔㄢ",
["chang"]="ㄔㄤ",
["chao"]="ㄔㄠ",
["che"]="ㄔㄜ",
["chen"]="ㄔㄣ",
["cheng"]="ㄔㄥ",
["chi"]="ㄔ",
["chong"]="ㄔㄨㄥ",
["chou"]="ㄔㄡ",
["chu"]="ㄔㄨ",
["chua"]="ㄔㄨㄚ",
["chuai"]="ㄔㄨㄞ",
["chuan"]="ㄔㄨㄢ",
["chuang"]="ㄔㄨㄤ",
["chui"]="ㄔㄨㄟ",
["chun"]="ㄔㄨㄣ",
["chuo"]="ㄔㄨㄛ",
["ci"]="ㄘ",
["cong"]="ㄘㄨㄥ",
["cou"]="ㄘㄡ",
["cu"]="ㄘㄨ",
["cuan"]="ㄘㄨㄢ",
["cui"]="ㄘㄨㄟ",
["cun"]="ㄘㄨㄣ",
["cuo"]="ㄘㄨㄛ",
["da"]="ㄉㄚ",
["dai"]="ㄉㄞ",
["dan"]="ㄉㄢ",
["dang"]="ㄉㄤ",
["dao"]="ㄉㄠ",
["de"]="ㄉㄜ",
["dei"]="ㄉㄟ",
["den"]="ㄉㄣ",
["deng"]="ㄉㄥ",
["di"]="ㄉㄧ",
["dian"]="ㄉㄧㄢ",
["diang"]="ㄉㄧㄤ",
["diao"]="ㄉㄧㄠ",
["die"]="ㄉㄧㄝ",
["ding"]="ㄉㄧㄥ",
["diu"]="ㄉㄧㄡ",
["dong"]="ㄉㄨㄥ",
["dou"]="ㄉㄡ",
["du"]="ㄉㄨ",
["duan"]="ㄉㄨㄢ",
["dui"]="ㄉㄨㄟ",
["dun"]="ㄉㄨㄣ",
["duo"]="ㄉㄨㄛ",
["e"]="ㄜ",
["ei"]="ㄟ",
["en"]="ㄣ",
["er"]="ㄦ",
["fa"]="ㄈㄚ",
["fan"]="ㄈㄢ",
["fang"]="ㄈㄤ",
["fei"]="ㄈㄟ",
["fen"]="ㄈㄣ",
["feng"]="ㄈㄥ",
["fo"]="ㄈㄛ",
["fou"]="ㄈㄡ",
["fu"]="ㄈㄨ",
["ga"]="ㄍㄚ",
["gai"]="ㄍㄞ",
["gan"]="ㄍㄢ",
["gang"]="ㄍㄤ",
["gao"]="ㄍㄠ",
["ge"]="ㄍㄜ",
["gei"]="ㄍㄟ",
["gen"]="ㄍㄣ",
["geng"]="ㄍㄥ",
["gong"]="ㄍㄨㄥ",
["gou"]="ㄍㄡ",
["gu"]="ㄍㄨ",
["gua"]="ㄍㄨㄚ",
["guai"]="ㄍㄨㄞ",
["guan"]="ㄍㄨㄢ",
["guang"]="ㄍㄨㄤ",
["gui"]="ㄍㄨㄟ",
["gun"]="ㄍㄨㄣ",
["guo"]="ㄍㄨㄛ",
["ha"]="ㄏㄚ",
["hai"]="ㄏㄞ",
["han"]="ㄏㄢ",
["hang"]="ㄏㄤ",
["hao"]="ㄏㄠ",
["he"]="ㄏㄜ",
["hei"]="ㄏㄟ",
["hen"]="ㄏㄣ",
["heng"]="ㄏㄥ",
["hong"]="ㄏㄨㄥ",
["hou"]="ㄏㄡ",
["hu"]="ㄏㄨ",
["hua"]="ㄏㄨㄚ",
["huai"]="ㄏㄨㄞ",
["huan"]="ㄏㄨㄢ",
["huang"]="ㄏㄨㄤ",
["hui"]="ㄏㄨㄟ",
["hun"]="ㄏㄨㄣ",
["huo"]="ㄏㄨㄛ",
["ji"]="ㄐㄧ",
["jia"]="ㄐㄧㄚ",
["jian"]="ㄐㄧㄢ",
["jiang"]="ㄐㄧㄤ",
["jiao"]="ㄐㄧㄠ",
["jie"]="ㄐㄧㄝ",
["jin"]="ㄐㄧㄣ",
["jing"]="ㄐㄧㄥ",
["jiong"]="ㄐㄩㄥ",
["jiu"]="ㄐㄧㄡ",
["ju"]="ㄐㄩ",
["juan"]="ㄐㄩㄢ",
["jue"]="ㄐㄩㄝ",
["jun"]="ㄐㄩㄣ",
["ka"]="ㄎㄚ",
["kai"]="ㄎㄞ",
["kan"]="ㄎㄢ",
["kang"]="ㄎㄤ",
["kao"]="ㄎㄠ",
["ke"]="ㄎㄜ",
["kei"]="ㄎㄟ",
["ken"]="ㄎㄣ",
["keng"]="ㄎㄥ",
["kong"]="ㄎㄨㄥ",
["kou"]="ㄎㄡ",
["ku"]="ㄎㄨ",
["kua"]="ㄎㄨㄚ",
["kuai"]="ㄎㄨㄞ",
["kuan"]="ㄎㄨㄢ",
["kuang"]="ㄎㄨㄤ",
["kui"]="ㄎㄨㄟ",
["kun"]="ㄎㄨㄣ",
["kuo"]="ㄎㄨㄛ",
["la"]="ㄌㄚ",
["lai"]="ㄌㄞ",
["lan"]="ㄌㄢ",
["lang"]="ㄌㄤ",
["lao"]="ㄌㄠ",
["le"]="ㄌㄜ",
["lei"]="ㄌㄟ",
["leng"]="ㄌㄥ",
["li"]="ㄌㄧ",
["lia"]="ㄌㄧㄚ",
["lian"]="ㄌㄧㄢ",
["liang"]="ㄌㄧㄤ",
["liao"]="ㄌㄧㄠ",
["lie"]="ㄌㄧㄝ",
["lin"]="ㄌㄧㄣ",
["ling"]="ㄌㄧㄥ",
["liu"]="ㄌㄧㄡ",
["lo"]="ㄌㄛ",
["long"]="ㄌㄨㄥ",
["lou"]="ㄌㄡ",
["lu"]="ㄌㄨ",
["luan"]="ㄌㄨㄢ",
["lun"]="ㄌㄨㄣ",
["luo"]="ㄌㄨㄛ",
["lü"]="ㄌㄩ",
["lüe"]="ㄌㄩㄝ",
["ma"]="ㄇㄚ",
["mai"]="ㄇㄞ",
["man"]="ㄇㄢ",
["mang"]="ㄇㄤ",
["mao"]="ㄇㄠ",
["me"]="ㄇㄜ",
["mei"]="ㄇㄟ",
["men"]="ㄇㄣ",
["meng"]="ㄇㄥ",
["mi"]="ㄇㄧ",
["mian"]="ㄇㄧㄢ",
["miao"]="ㄇㄧㄠ",
["mie"]="ㄇㄧㄝ",
["min"]="ㄇㄧㄣ",
["ming"]="ㄇㄧㄥ",
["miu"]="ㄇㄧㄡ",
["mo"]="ㄇㄛ",
["mou"]="ㄇㄡ",
["mu"]="ㄇㄨ",
["na"]="ㄋㄚ",
["nai"]="ㄋㄞ",
["nan"]="ㄋㄢ",
["nang"]="ㄋㄤ",
["nao"]="ㄋㄠ",
["ne"]="ㄋㄜ",
["nei"]="ㄋㄟ",
["nen"]="ㄋㄣ",
["neng"]="ㄋㄥ",
["ni"]="ㄋㄧ",
["nia"]="ㄋㄧㄚ",
["nian"]="ㄋㄧㄢ",
["niang"]="ㄋㄧㄤ",
["niao"]="ㄋㄧㄠ",
["nie"]="ㄋㄧㄝ",
["nin"]="ㄋㄧㄣ",
["ning"]="ㄋㄧㄥ",
["niu"]="ㄋㄧㄡ",
["nong"]="ㄋㄨㄥ",
["nou"]="ㄋㄡ",
["nu"]="ㄋㄨ",
["nuan"]="ㄋㄨㄢ",
["nun"]="ㄋㄨㄣ",
["nuo"]="ㄋㄨㄛ",
["nü"]="ㄋㄩ",
["nüe"]="ㄋㄩㄝ",
["o"]="ㄛ",
["ou"]="ㄡ",
["pa"]="ㄆㄚ",
["pai"]="ㄆㄞ",
["pan"]="ㄆㄢ",
["pang"]="ㄆㄤ",
["pao"]="ㄆㄠ",
["pei"]="ㄆㄟ",
["pen"]="ㄆㄣ",
["peng"]="ㄆㄥ",
["pi"]="ㄆㄧ",
["pian"]="ㄆㄧㄢ",
["piao"]="ㄆㄧㄠ",
["pie"]="ㄆㄧㄝ",
["pin"]="ㄆㄧㄣ",
["ping"]="ㄆㄧㄥ",
["po"]="ㄆㄛ",
["pou"]="ㄆㄡ",
["pu"]="ㄆㄨ",
["qi"]="ㄑㄧ",
["qia"]="ㄑㄧㄚ",
["qian"]="ㄑㄧㄢ",
["qiang"]="ㄑㄧㄤ",
["qiao"]="ㄑㄧㄠ",
["qie"]="ㄑㄧㄝ",
["qin"]="ㄑㄧㄣ",
["qing"]="ㄑㄧㄥ",
["qiong"]="ㄑㄩㄥ",
["qiu"]="ㄑㄧㄡ",
["qu"]="ㄑㄩ",
["quan"]="ㄑㄩㄢ",
["que"]="ㄑㄩㄝ",
["qun"]="ㄑㄩㄣ",
["ran"]="ㄖㄢ",
["rang"]="ㄖㄤ",
["rao"]="ㄖㄠ",
["re"]="ㄖㄜ",
["ren"]="ㄖㄣ",
["reng"]="ㄖㄥ",
["ri"]="ㄖ",
["rong"]="ㄖㄨㄥ",
["rou"]="ㄖㄡ",
["ru"]="ㄖㄨ",
["ruan"]="ㄖㄨㄢ",
["rui"]="ㄖㄨㄟ",
["run"]="ㄖㄨㄣ",
["ruo"]="ㄖㄨㄛ",
["sa"]="ㄙㄚ",
["sai"]="ㄙㄞ",
["san"]="ㄙㄢ",
["sang"]="ㄙㄤ",
["sao"]="ㄙㄠ",
["se"]="ㄙㄜ",
["sei"]="ㄙㄟ",
["sen"]="ㄙㄣ",
["seng"]="ㄙㄥ",
["sha"]="ㄕㄚ",
["shai"]="ㄕㄞ",
["shan"]="ㄕㄢ",
["shang"]="ㄕㄤ",
["shao"]="ㄕㄠ",
["she"]="ㄕㄜ",
["shei"]="ㄕㄟ",
["shen"]="ㄕㄣ",
["sheng"]="ㄕㄥ",
["shi"]="ㄕ",
["shong"]="ㄕㄨㄥ",
["shou"]="ㄕㄡ",
["shu"]="ㄕㄨ",
["shua"]="ㄕㄨㄚ",
["shuai"]="ㄕㄨㄞ",
["shuan"]="ㄕㄨㄢ",
["shuang"]="ㄕㄨㄤ",
["shui"]="ㄕㄨㄟ",
["shun"]="ㄕㄨㄣ",
["shuo"]="ㄕㄨㄛ",
["si"]="ㄙ",
["song"]="ㄙㄨㄥ",
["sou"]="ㄙㄡ",
["su"]="ㄙㄨ",
["suan"]="ㄙㄨㄢ",
["sui"]="ㄙㄨㄟ",
["sun"]="ㄙㄨㄣ",
["suo"]="ㄙㄨㄛ",
["ta"]="ㄊㄚ",
["tai"]="ㄊㄞ",
["tan"]="ㄊㄢ",
["tang"]="ㄊㄤ",
["tao"]="ㄊㄠ",
["te"]="ㄊㄜ",
["teng"]="ㄊㄥ",
["ti"]="ㄊㄧ",
["tian"]="ㄊㄧㄢ",
["tiao"]="ㄊㄧㄠ",
["tie"]="ㄊㄧㄝ",
["ting"]="ㄊㄧㄥ",
["tong"]="ㄊㄨㄥ",
["tou"]="ㄊㄡ",
["tu"]="ㄊㄨ",
["tuan"]="ㄊㄨㄢ",
["tui"]="ㄊㄨㄟ",
["tun"]="ㄊㄨㄣ",
["tuo"]="ㄊㄨㄛ",
["wa"]="ㄨㄚ",
["wai"]="ㄨㄞ",
["wan"]="ㄨㄢ",
["wang"]="ㄨㄤ",
["wei"]="ㄨㄟ",
["wen"]="ㄨㄣ",
["weng"]="ㄨㄥ",
["wo"]="ㄨㄛ",
["wu"]="ㄨ",
["xi"]="ㄒㄧ",
["xia"]="ㄒㄧㄚ",
["xian"]="ㄒㄧㄢ",
["xiang"]="ㄒㄧㄤ",
["xiao"]="ㄒㄧㄠ",
["xie"]="ㄒㄧㄝ",
["xin"]="ㄒㄧㄣ",
["xing"]="ㄒㄧㄥ",
["xiong"]="ㄒㄩㄥ",
["xiu"]="ㄒㄧㄡ",
["xu"]="ㄒㄩ",
["xuan"]="ㄒㄩㄢ",
["xue"]="ㄒㄩㄝ",
["xun"]="ㄒㄩㄣ",
["ya"]="ㄧㄚ",
["yan"]="ㄧㄢ",
["yang"]="ㄧㄤ",
["yao"]="ㄧㄠ",
["ye"]="ㄧㄝ",
["yi"]="ㄧ",
["yin"]="ㄧㄣ",
["ying"]="ㄧㄥ",
["yong"]="ㄩㄥ",
["you"]="ㄧㄡ",
["yu"]="ㄩ",
["yuan"]="ㄩㄢ",
["yue"]="ㄩㄝ",
["yun"]="ㄩㄣ",
["za"]="ㄗㄚ",
["zai"]="ㄗㄞ",
["zan"]="ㄗㄢ",
["zang"]="ㄗㄤ",
["zao"]="ㄗㄠ",
["ze"]="ㄗㄜ",
["zei"]="ㄗㄟ",
["zen"]="ㄗㄣ",
["zeng"]="ㄗㄥ",
["zha"]="ㄓㄚ",
["zhai"]="ㄓㄞ",
["zhan"]="ㄓㄢ",
["zhang"]="ㄓㄤ",
["zhao"]="ㄓㄠ",
["zhe"]="ㄓㄜ",
["zhei"]="ㄓㄟ",
["zhen"]="ㄓㄣ",
["zheng"]="ㄓㄥ",
["zhi"]="ㄓ",
["zhong"]="ㄓㄨㄥ",
["zhou"]="ㄓㄡ",
["zhu"]="ㄓㄨ",
["zhua"]="ㄓㄨㄚ",
["zhuai"]="ㄓㄨㄞ",
["zhuan"]="ㄓㄨㄢ",
["zhuang"]="ㄓㄨㄤ",
["zhui"]="ㄓㄨㄟ",
["zhun"]="ㄓㄨㄣ",
["zhuo"]="ㄓㄨㄛ",
["zi"]="ㄗ",
["zong"]="ㄗㄨㄥ",
["zou"]="ㄗㄡ",
["zu"]="ㄗㄨ",
["zuan"]="ㄗㄨㄢ",
["zui"]="ㄗㄨㄟ",
["zun"]="ㄗㄨㄣ",
["zuo"]="ㄗㄨㄛ",

-- Initial constants
["b"]  = "ㄅ",
["p"]  = "ㄆ",
["m"]  = "ㄇ",
["f"]  = "ㄈ",
["d"]  = "ㄉ",
["t"]  = "ㄊ",
["n"]  = "ㄋ",
["l"]  = "ㄌ",
["g"]  = "ㄍ",
["k"]  = "ㄎ",
["h"]  = "ㄏ",
["j"]  = "ㄐ",
["q"]  = "ㄑ",
["x"]  = "ㄒ",
["zh"] = "ㄓ",
["ch"] = "ㄔ",
["sh"] = "ㄕ",
["r"]  = "ㄖ",
["z"]  = "ㄗ",
["c"]  = "ㄘ",
["s"]  = "ㄙ",

["y"]  = "ㄧ",
["w"]  = "ㄨ",
}


local function shuangpin_to_pinyin(code)
  res = SHUANGPIN_TO_PINYIN[code]
  if res ~= nil then
    return res
  end
  return code
end

function bopomofo.shuangpin_to_quanpin_full(code)
  local res = ""
  for i = 1, #code, 2 do
    local syllable = code:sub(i, i+1)
    local py = shuangpin_to_pinyin(syllable)
    local sep = (#syllable == 2) and " " or ""
    res = res .. py .. sep
  end
  return res
end

-- Lua function to convert toneless pinyin + tone number to tonal pinyin
function to_tonal_pinyin(toneless, tone)
    -- Return as-is if tone is 0
    if tone == "" then return toneless end

    -- vowel map for tones: a, e, i, o, u, v (v = ü)
    local vowels = {
        a = {"ā","á","ǎ","à"},
        e = {"ē","é","ě","è"},
        i = {"ī","í","ǐ","ì"},
        o = {"ō","ó","ǒ","ò"},
        u = {"ū","ú","ǔ","ù"},
        v = {"ǖ","ǘ","ǚ","ǜ"}, -- ü
    }

    -- tone number map
    local tones = {
      s = 0,
      l = 1,
      r = 2,
      v = 3,
      j = 4,
    }

    -- convert tone index from 1-4 to Lua index 1-4
    local tone_index = 6
    if tones[tone] then
      tone_index = tones[tone]
    end

    if tone_index < 1 then
       return toneless
    elseif tone_index > 4 then
       return toneless .. "?" -- invalid tone, return as-is
    end

    toneless = toneless:gsub("ü", "v")

    local function replace_vowel(v)
        local lower = v:lower()
        if vowels[lower] then
            return vowels[lower][tone_index]
        else
            return v
        end
    end

    local main_vowel

    -- priority: a > o > e
    main_vowel = toneless:match("[aA]") or toneless:match("[oO]") or toneless:match("[eE]")

    if not main_vowel then
        -- handle i/u/ü: pick the last occurrence
        local i_pos = toneless:match(".*()[iI]") or 0
        local u_pos = toneless:match(".*()[uU]") or 0
        local v_pos = toneless:match(".*()[vV]") or 0
        local last_pos = math.max(i_pos, u_pos, v_pos)
        if last_pos > 0 then
            main_vowel = toneless:sub(last_pos, last_pos)
        else
            return toneless
        end
    end

    if not main_vowel then
        return toneless -- no vowel found
    end

    -- replace the first occurrence of main_vowel with tonal mark
    local result, n = toneless:gsub(main_vowel, replace_vowel, 1)
    return result
end

function bopomofo.sanpin_to_quanpin_full(code)
  local res = ""
  for i = 1, #code, 3 do
    local syllable = code:sub(i, i+1)
    local tone = code:sub(i+2,i+2)
    local py = shuangpin_to_pinyin(syllable)
    local tonal_py = to_tonal_pinyin(py, tone)
    local sep = (#syllable + #tone == 3) and " " or ""
    res = res .. tonal_py .. sep
  end
  return res
end

local function pinyin_to_zhuyin(pinyin)
  res = PINYIN_TO_ZHUYIN[pinyin]
  if res ~= nil then
    return res
  end
  return pinyin
end

function bopomofo.shuangpin_to_zhuyin_full(code)
  local res = ""
  for i = 1, #code, 2 do
    local syllable = code:sub(i, i+1)
    local py = shuangpin_to_pinyin(syllable)
    local sep = (#syllable == 2) and "·" or ""
    res = res .. pinyin_to_zhuyin(py) .. sep
  end
  return res
end

function bopomofo.to_cangjie(code)
  local cj_map = {
    a="日", b="月", c="金", d="木", e="水", f="火", g="土", h="竹",
    i="戈", j="十", k="大", l="中", m="一", n="弓", o="人", p="心",
    q="手", r="口", s="尸", t="廿", u="山", v="女", w="田", x="難",
    y="卜", z="重"
  }
  local res = ""
  for i = 1, #code do
    local c = code:sub(i,i)
    res = res .. (cj_map[c] or c)
  end
  return res
end

return bopomofo

